services:
  bot:
    build:
      context: .
      tags:
        - "discord-music-bot"
    volumes:
      - .:/code
    depends_on:
      lavalink:
        condition: service_healthy
    env_file:
      - .env

  lavalink:
    image: fredboat/lavalink:4
    volumes:
      - ./lavalink.yaml:/opt/Lavalink/application.yaml
    healthcheck:
      test: 'echo lavalink'
      interval: 1s
