services:
  bot:
    build:
      context: .
    image: discord-music-bot
    volumes:
      - .:/code
    depends_on:
      lavalink:
        condition: service_healthy
    env_file:
      - .env
    restart:
      unless-stopped

  lavalink:
    image: fredboat/lavalink:4
    volumes:
      - ./lavalink.yaml:/opt/Lavalink/application.yaml
    healthcheck:
      test: 'echo lavalink'
      interval: 1s
    restart:
      unless-stopped

  yt-cipher:
    image: ghcr.io/kikkia/yt-cipher:master
    ports:
      - "8001:8000"
    restart:
      unless-stopped
